# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
# source: books.sql
import dataclasses
from typing import Iterator, Optional

import sqlalchemy

from sql.code import models


LIST_BOOK_OVER_PRICE = """-- name: list_book_over_price \\:many
SELECT
        b.title
     ,	a.name
     ,	b.price
FROM
    books b
        LEFT JOIN
    authors a
    ON	1 = 1
        AND b.author_id = a.id
WHERE
    price > :p1
ORDER BY
    b.title
"""


@dataclasses.dataclass()
class ListBookOverPriceRow:
    title: str
    name: Optional[str]
    price: int


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def list_book_over_price(self, *, price: int) -> Iterator[ListBookOverPriceRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_BOOK_OVER_PRICE), {"p1": price})
        for row in result:
            yield ListBookOverPriceRow(
                title=row[0],
                name=row[1],
                price=row[2],
            )
