# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
import dataclasses
import datetime
from typing import Optional
import uuid


@dataclasses.dataclass()
class Author:
    id: uuid.UUID
    name: str
    bio: Optional[str]


@dataclasses.dataclass()
class Book:
    id: uuid.UUID
    title: str
    price: int
    author_id: uuid.UUID
    created_at: datetime.datetime
